#!/usr/bin/env python3
"""Regenerate fused_render/publish/pyodide_imports.json from the pinned Pyodide lock.

The publish eligibility scan has to answer "can a browser Python runtime import
this?" **offline** — it runs on every Publish-page load, long before anything is
downloaded. The honest source for that answer is the Pyodide distribution's own
``pyodide-lock.json``, which lists the top-level module names every package
provides. So we check in a projection of it, generated by this script, instead of
hand-maintaining a guess that would drift from what a publish actually vendors.

Run it whenever ``pyodide_dist.PYODIDE_VERSION`` moves:

    python scripts/refresh_pyodide_imports.py

``tests/test_publish_pyodide_dist.py`` holds the checked-in file to the pinned
version when the network is reachable, and skips otherwise — so a stale map is a
red test on a connected machine, never a silent wrong answer.
"""

import json
import os
import sys
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from fused_render.publish.pyodide_dist import PYODIDE_VERSION, lock_url  # noqa: E402

OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "fused_render", "publish", "pyodide_imports.json",
)


def build(lock: dict) -> dict:
    """``{import name: package name}`` for every package in the distribution.

    First writer wins on a collision so the mapping is deterministic across runs;
    collisions are vanishingly rare (a top-level module name is effectively owned
    by one distribution) and picking either side would be equally defensible.
    """
    imports: dict[str, str] = {}
    for name in sorted(lock["packages"]):
        for mod in lock["packages"][name].get("imports", []):
            imports.setdefault(mod, name)
    return imports


def main() -> int:
    with urllib.request.urlopen(lock_url(PYODIDE_VERSION), timeout=60) as r:
        lock = json.load(r)
    payload = {
        "pyodide_version": PYODIDE_VERSION,
        "python_version": lock["info"]["python"],
        "imports": build(lock),
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=1, sort_keys=True)
        f.write("\n")
    print(f"{OUT}: {len(payload['imports'])} imports from Pyodide {PYODIDE_VERSION}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
