"""The Pyodide distribution: pin it, fetch it once, vendor what an app needs.

A published rung-1 app runs its Python in the reader's browser, so the runtime
has to be *in the deployment*. The choice was CDN-or-bundled and this module is
the bundled half: the site is self-contained, it works behind a strict CSP, it
keeps working when a third-party CDN does not, and after the first load it works
with no network at all. The cost is upload bytes, which is why only the packages
the app's imports actually resolve to are vendored — a stdlib-only app carries
the core distribution and nothing else.

Fetching happens **here on the author's machine**, once per Pyodide version, into
``~/.fused-render/publish/pyodide/<version>/``. Every later publish of every app
copies out of that cache, so the network cost is paid once and a publish with a
warm cache touches nothing but the provider.

Two files decide what "available in Pyodide" means, and they must agree:

* ``pyodide-lock.json`` — the distribution's own index, the authority. It names
  each package's wheel and, crucially, the top-level modules that package
  provides. Resolution against it is exact, and a miss is a loud build error.
* ``pyodide_imports.json`` — a checked-in projection of that same lock, so the
  eligibility scan can answer "would this import work in a browser?" **offline**,
  on every Publish-page load, before anything is downloaded. Regenerated by
  ``scripts/refresh_pyodide_imports.py``; a test pins it to the version below.

The version is pinned, never floating. A page that renders correctly for a reader
today must render the same way after the author re-publishes, and a Pyodide minor
bump can change a package version under them. Moving the pin is a deliberate
commit that regenerates the import map with it.
"""

from __future__ import annotations

import json
import os
import shutil
import tarfile
import tempfile
import urllib.error
import urllib.request

from fused_render.publish.adapter import PublishError

#: The pinned Pyodide release. Moving it means re-running
#: ``scripts/refresh_pyodide_imports.py`` in the same commit.
PYODIDE_VERSION = "314.0.6"

#: Files from ``pyodide-core`` without which a published site cannot boot. A
#: missing one is a hard error naming it, because the alternative is a deployment
#: that uploads cleanly and then shows a reader a blank page.
CORE_REQUIRED: tuple[str, ...] = (
    "pyodide.js",
    "pyodide.asm.wasm",
    "python_stdlib.zip",
    "pyodide-lock.json",
)

#: Files the loader wants but whose NAMES move between releases — 314.x renamed
#: the Emscripten glue from ``pyodide.asm.js`` to ``pyodide.asm.mjs``. Copied
#: when present and skipped when not, so a rename is absorbed rather than being a
#: publish that stops working the day the pin moves. The required set above is
#: what actually guards the outcome.
CORE_OPTIONAL: tuple[str, ...] = (
    "pyodide.mjs",
    "pyodide.asm.js",
    "pyodide.asm.mjs",
    "package.json",
)

#: Everything a site build copies, present or not.
CORE_FILES: tuple[str, ...] = CORE_REQUIRED + CORE_OPTIONAL

_RELEASE = "https://github.com/pyodide/pyodide/releases/download"
_CDN = "https://cdn.jsdelivr.net/pyodide"


def lock_url(version: str = PYODIDE_VERSION) -> str:
    return f"{_CDN}/v{version}/full/pyodide-lock.json"


def _core_url(version: str) -> str:
    return f"{_RELEASE}/{version}/pyodide-core-{version}.tar.bz2"


def _wheel_url(version: str, file_name: str) -> str:
    return f"{_CDN}/v{version}/full/{file_name}"


def cache_root(version: str = PYODIDE_VERSION) -> str:
    """``<home>/publish/pyodide/<version>`` — shared by every app on this machine.

    Under ``shell.storage.home_dir()`` rather than Application Support so it is
    branch-nested and ``FUSED_RENDER_HOME``-overridable like the rest of our user
    data: a test never touches the real cache, and two branches never fight over
    one version's directory.
    """
    from fused_render.shell.storage import home_dir

    return os.path.join(home_dir(), "publish", "pyodide", version)


def is_cached(version: str = PYODIDE_VERSION) -> bool:
    """True when the core distribution is already unpacked and complete.

    Completeness is checked file by file rather than by the directory existing,
    so an interrupted download leaves a state that re-fetches instead of one that
    publishes a site missing ``pyodide.asm.wasm``.
    """
    root = cache_root(version)
    return all(os.path.isfile(os.path.join(root, name)) for name in CORE_REQUIRED)


def _download(url: str, dest: str, *, what: str) -> None:
    """Fetch ``url`` to ``dest`` via a temp file in the same directory.

    Never leaves a partial file at ``dest``: an interrupted fetch leaves only the
    temp file, so :func:`is_cached` keeps saying no and the retry works.
    """
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(dest), prefix=".download-")
    os.close(fd)
    try:
        with urllib.request.urlopen(url, timeout=120) as r, open(tmp, "wb") as f:
            shutil.copyfileobj(r, f)
        os.replace(tmp, dest)
    except (urllib.error.URLError, OSError, TimeoutError) as exc:
        raise PublishError(
            f"could not download {what} from {url}: {exc}. Publishing bundles a Python "
            "runtime into the app, which has to be fetched once per Pyodide version; "
            "check your connection and try again."
        ) from exc
    finally:
        if os.path.exists(tmp):
            os.remove(tmp)


def ensure_core(version: str = PYODIDE_VERSION) -> str:
    """Make sure the core distribution is cached, and return its directory.

    A no-op when it already is, so only the first publish on a machine pays for
    the download.
    """
    root = cache_root(version)
    if is_cached(version):
        return root
    os.makedirs(root, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="fused-pyodide-") as work:
        archive = os.path.join(work, "core.tar.bz2")
        _download(_core_url(version), archive, what=f"the Pyodide {version} runtime")
        try:
            with tarfile.open(archive, "r:bz2") as tar:
                # Extract only what a site loads, flattened: the tarball nests
                # everything under a `pyodide/` prefix, and taking members by
                # basename also refuses any entry whose path tried to escape.
                wanted = set(CORE_FILES)
                for member in tar.getmembers():
                    base = os.path.basename(member.name)
                    if not member.isfile() or base not in wanted:
                        continue
                    src = tar.extractfile(member)
                    if src is None:
                        continue
                    with src, open(os.path.join(root, base), "wb") as out:
                        shutil.copyfileobj(src, out)
        except (tarfile.TarError, OSError) as exc:
            raise PublishError(
                f"the downloaded Pyodide {version} archive could not be unpacked: {exc}"
            ) from exc
    missing = [n for n in CORE_REQUIRED if not os.path.isfile(os.path.join(root, n))]
    if missing:
        raise PublishError(
            f"the Pyodide {version} download is missing {', '.join(missing)} — the release "
            "layout may have changed. Nothing was published."
        )
    return root


def read_lock(version: str = PYODIDE_VERSION) -> dict:
    """The cached distribution's ``pyodide-lock.json``, fetching the core if needed."""
    root = ensure_core(version)
    with open(os.path.join(root, "pyodide-lock.json"), encoding="utf-8") as f:
        return json.load(f)


def resolve_packages(
    names: list[str], *, version: str = PYODIDE_VERSION, lock: dict | None = None
) -> list[str]:
    """Expand ``names`` to every wheel that must ship, dependencies included.

    Pyodide's ``loadPackage`` can resolve dependencies itself — but only by going
    to the network for them, which is exactly what bundling exists to avoid. So
    the closure is computed here and every wheel in it is vendored, leaving the
    published page with nothing to fetch.

    :raises PublishError: a name the distribution does not carry. Loud, and at
        build time on the author's machine — the alternative is a page that boots
        in a reader's browser and then fails to import.
    """
    lock = lock if lock is not None else read_lock(version)
    packages = lock["packages"]
    out: dict[str, None] = {}
    queue = list(names)
    while queue:
        name = queue.pop(0)
        if name in out:
            continue
        entry = packages.get(name)
        if entry is None:
            raise PublishError(
                f"the Pyodide {version} distribution has no package named {name!r}, so it "
                "cannot be bundled into a published app. This app needs a target that runs "
                "real CPython."
            )
        out[name] = None
        queue.extend(entry.get("depends", []))
    return sorted(out)


def ensure_wheels(names: list[str], *, version: str = PYODIDE_VERSION) -> list[str]:
    """Cache each resolved package's wheel and return the cached file paths.

    Downloads are per wheel and idempotent, so adding one import to an app
    re-fetches one file rather than the distribution.
    """
    lock = read_lock(version)
    root = cache_root(version)
    paths: list[str] = []
    for name in resolve_packages(names, version=version, lock=lock):
        file_name = lock["packages"][name]["file_name"]
        dest = os.path.join(root, "packages", os.path.basename(file_name))
        if not os.path.isfile(dest):
            _download(_wheel_url(version, file_name), dest, what=f"the {name} wheel")
        paths.append(dest)
    return paths


def import_map() -> dict[str, str]:
    """``{import name: Pyodide package name}`` from the checked-in projection.

    Offline and cheap — this is what the eligibility scan consults on every
    Publish-page load. The live lock is the authority at publish time; this is its
    shadow, and ``scripts/refresh_pyodide_imports.py`` is what keeps them equal.
    """
    with open(
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "pyodide_imports.json"),
        encoding="utf-8",
    ) as f:
        return json.load(f)["imports"]
